---
namespace: ffrias9

name: awx_jobs

version: 1.7.1

authors: Francisco José Frías Martín <fp_franciscofrias@ciudadjardin.org>

min_ansible_version: 2.12.0

description: Plugins to interact with the AWX API

license:
  - MIT

tags:
  - cloud
  - infrastructure
  - awx
  - ansible
  - automation

dependencies: {}

repository: https://github.com/ffrias9/ansible_collections/blob/main/ffrias9/awx_jobs

documentation: https://github.com/ffrias9/ansible_collections/blob/main/ffrias9/awx_jobs/README.md

homepage: https://github.com/ffrias9/ansible_collections/

issues: https://github.com/ffrias9/ansible_collections/issues

readme: README.md

platforms:
  - name: Red Hat
    versions:
      - all
  - name: Debian
    versions:
      - all
